[package]
name = "license_microservice"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
mongodb = "3"
serde = "1.0.216"
dotenv = "0.15.0"
chrono = "0.4.39"
futures = "0.3.31"
tokio = "1.42.0"
env_logger = "0.11.6"
log = "0.4.22"